### ISSUE TITLE
Feature request: Check files against the hash

### ISSUE THREAD

**Issue by Joshfindit** [JohnDoee/autotorrent#1]
Most old content and content that has been curated in to a Library has been renamed, subtracted from, and added to.

To use autotorrent on these files, it would be necessary to check the contents in full using piece hashes.
Worst-case scenario, some files are missing or some of the data within the files is missing, but if there is a peer who has the 3% that you are missing, and you have the other 97%, then both could have 100% by 'seeding' the incomplete torrent.

**Comment by JohnDoee** [comment]
To make sure I understand the request correctly, can you please compare it with my example and maybe give a counter example.

**Example:**
You have downloaded the Pioneer One season pack from http://vodo.net/download/torrent/127 (it has 6 episodes and a few small files).

* The episodes have been renamed to something that does not match the original name
* One of the episodes went missing
* One episode is corrupted
* All the episodes NOT missing still have the **original filesize**
* (optional but I think this is a good enforcement) All files have their original file extension

The directory listing might look like this:
* Pioneer one (folder)
  * _E1.mkv_ (file, original filesize, uncorrupted)
  * _E2.mkv_ (file, original filesize, uncorrupted)
  * _E4.mkv_ (file, original filesize, corrupted)
  * _E5.mkv_ (file, original filesize, uncorrupted)
  * _E6.mkv_ (file, original filesize, uncorrupted)

AutoTorrent should then be able to ensure episode 1-2,4-6 are the correct episodes even though one is corrupted and their names are messed up.

**Comment by Joshfindit** [comment]
Yes, that's an excellent example.

To add to the example;
When you downloaded it, Sickbeard processed Pioneer One in to a library location: /media/Video/TV/Pioneer One/Season 01/
Sickbeard did not move "Support.Pioneer.One!.URL" or "vodo.nfo", and later deleted those two smaller files.
It also added it's own .nfo files for each episode (/media/Video/TV/Pioneer One/Season 01/E1.mkv, /media/Video/TV/Pioneer One/Season 01/E1.nfo, and so on)

Somewhere along the way, there was a hard drive issue and E3 was lost along with a few bytes of E4.
Now, you have a new internet connection, new server, or something else, and want to seed what you have for everyone's benefit.

autotorrent steps in, does the heavy lifting, and after you grab the rest of the data automatically, you're seeding 100% just like you wanted to.
