### ISSUE TITLE
no such option: --create_config

### ISSUE THREAD

**Issue by adamwinn** [JohnDoee/autotorrent#12]
Following the steps in the readme, I get:
```
user@server460:~/.local/bin$ autotorrent-env/bin/pip --create_config autotorrent-env/autotorrent.conf

Usage:   
  pip <command> [options]

no such option: --create_config
```

Am I missing a step?  Or can you provide what a sample config file looks like and I can just create it myself?

**Comment by JohnDoee** [comment]
pip installs stuff, you have to run the autotorrent script to do the autotorrent stuff

e.g. to create config:
`autotorrent-env/bin/autotorrent --create_config`

to scan your data:
`autotorrent-env/bin/autotorrent -r`

to add files to your client:
`autotorrent-env/bin/autotorrent -a path/to/torrents/*.torrent`

**Comment by adamwinn** [comment]
Looks like there's a typo in the readme then:

```
Create the configuration file

autotorrent-env/bin/pip --create_config autotorrent-env/autotorrent.conf
```
