### ISSUE TITLE
[Feature] Enable per-disk store_path

### ISSUE THREAD

**Issue by d2dyno** [JohnDoee/autotorrent#14]
I have a many-device array. I'm interested in using this code to cross-seed files, but having one store_path won't work, as I get `OSError: [Errno 18] Invalid cross-device link`.

The way my system is setup, is each hard drive has it's own slot under `/mnt/diskX`, so for example, if I want to `ln` files from `/mnt/disk5`, `/mnt/disk5` has to be the destination, not a parent folder like `/mnt/disks`. Is it already possible to do that with this application in the config, and if not, can it be coded in? I'm willing to pay for this feature.

**Comment by JohnDoee** [comment]
Using soft links should solve this issue, is it important to you to use hard-links instead ?

    link_type = soft

**Comment by d2dyno** [comment]
Well, I was under the wrong impression this would work with hard links, but I just tried with soft and it works great!!! Thanks for the comment :)
