### ISSUE TITLE
Qbittorent 

### ISSUE THREAD

**Issue by forsomefun2** [JohnDoee/autotorrent#23]
Native support for qbittorent would be nice 

Right now I just made a secondary fake rtorrent client so the program will run, and create the systemlinks.

I'm planning on the adding the torrents manually through qbittorent, and maybe skipping hash check

**Comment by JohnDoee** [comment]
Which version of qbittorrent are you using ?

**Comment by forsomefun2** [comment]
4.1.4 the newest released version, on linux

I actually ran into a few problems with my initial plan. Namely how the .torrents files where named when extracted  from an old server's rtorrent.

**Comment by JohnDoee** [comment]
So, the current develop branch has qbittorrent support if you want to test it out. I need to do a bit more testing to roll it out as a release but initial tests seem to work fine.

> I don't think it works if you change the type of database

You're right and the thought never actually struck me that someone would mix it around.

There is a lot of confusing stuff in autotorrent because features were attached along the way. The config file does not really match how users use autotorrent.

**Comment by JohnDoee** [comment]
Http auth works by just adding the user and pass to the url, e.g. http://username:password@qbittorrent.example.com

The SSL stuff is working as intended, not sure I want to disable security features :smile:

**Comment by forsomefun2** [comment]
I see I added 
1000 torrents without issue. 

So it seems to be working on initial testing.

**Comment by JohnDoee** [comment]
Thanks for testing

**Comment by JohnDoee** [comment]
You're right, that's qbittorrent output. Removed my debug code.

**Comment by d2dyno** [comment]
Perfect! Also for the tally, I've added 347 torrents to qBittorrent without issue thus far. Excellent work!

**Comment by forsomefun2** [comment]
There is a lot of confusing stuff in autotorrent because features were attached along the way. The config file does not really match how users use autotorrent.

 autotorrent-env/bin/autotorrent -h

**Comment by d2dyno** [comment]
@forsomefun2 I plan on adding these to the readme. However, this does not pertain to this issue (qbittorrent).
