### ISSUE TITLE
Tranmission SSL error

### ISSUE THREAD

**Issue by snickerp** [JohnDoee/autotorrent#24]
HTTPSConnectionPool(host='127.0.0.1', port=9093): Max retries exceeded with url: / (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_record', 'wrong version number')],)",),))

SSL is given via letsencrypt 
URL =  url = https://name:pass@127.0.0.1:9093

**Comment by JohnDoee** [comment]
SSL and Python has been a headache for some time.

Can you try `autotorrent-env/bin/pip install ndg-httpsclient` and see if that fixes it?

**Comment by snickerp** [comment]
Same error this is the full error
'Traceback (most recent call last):
File "/usr/local/bin/autotorrent", line 11, in <module>
sys.exit(commandline_handler())
File "/usr/local/lib/python3.6/dist-packages/autotorrent/cmd.py", line 266,
in commandline_handler
proxy_test_result = client.test_connection()
File
"/usr/local/lib/python3.6/dist-packages/autotorrent/clients/transmission.py",
line 106, in test_connection
session_data = self.call('session-get')
File
"/usr/local/lib/python3.6/dist-packages/autotorrent/clients/transmission.py",
line 47, in call
r = self._call(method, **kwargs)
File
"/usr/local/lib/python3.6/dist-packages/autotorrent/clients/transmission.py",
line 41, in _call
return requests.post(self.url, data=json.dumps({'method': method,
'arguments': kwargs}), headers={'X-Transmission-Session-Id':
self._session_id})
File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 112, in
post
return request('post', url, data=data, json=json, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/api.py", line 58, in
request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line
508, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/sessions.py", line
618, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/requests/adapters.py", line
506, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='127.0.0.1',
port=9093): Max retries exceeded with url: / (Caused by
SSLError(SSLError("bad handshake: Error([('SSL routines',
'ssl3_get_record', 'wrong version number')],)",),))'

**Comment by JohnDoee** [comment]
Autotorrent uses Transmission Web to control Transmission and, as far as I can see, that one doesn't support SSL natively.

So, try using http instead of https. If that doesn't work, make sure you're using the correct port.

**Comment by JohnDoee** [comment]
If this didn't fix it, feel free to re-open the issue.
